from my_envs.envs.halfcheetah_modified_leg import HalfCheetahEnv_modified_leg


from my_envs.envs.half_cheetah_modified import HalfCheetahModifiedBaseEnv
from my_envs.envs.half_cheetah_modified import HalfCheetahModifiedMultiEnv
from my_envs.envs.half_cheetah_modified import HalfCheetahModifiedMassEnv
from my_envs.envs.half_cheetah_modified import HalfCheetahModifiedMotorEnv
from my_envs.envs.half_cheetah_modified import HalfCheetahModifiedJointFrictionEnv
from my_envs.envs.half_cheetah_modified import HalfCheetahModifiedGroundFrictionEnv
from my_envs.envs.half_cheetah_modified import HalfCheetahModifiedDampingEnv
from my_envs.envs.half_cheetah_modified import HalfCheetahModifiedStiffnessEnv

from my_envs.envs.half_cheetah_modified131 import HalfCheetahModifiedBaseEnv131
from my_envs.envs.half_cheetah_modified131 import HalfCheetahModifiedMultiEnv131
from my_envs.envs.half_cheetah_modified131 import HalfCheetahModifiedMassEnv131
from my_envs.envs.half_cheetah_modified131 import HalfCheetahModifiedMotorEnv131
from my_envs.envs.half_cheetah_modified131 import HalfCheetahModifiedJointFrictionEnv131
from my_envs.envs.half_cheetah_modified131 import HalfCheetahModifiedGroundFrictionEnv131
from my_envs.envs.half_cheetah_modified131 import HalfCheetahModifiedDampingEnv131
from my_envs.envs.half_cheetah_modified131 import HalfCheetahModifiedStiffnessEnv131
